### ISSUE TITLE
An issue about memory

### ISSUE THREAD

**Issue by Malanced** [azuwis/pianotrans#1]
Hi,

I had no idea why I failed to use it. It just shows "fatal: Memory allocation failure" and sometimes it ends with "not enough memory Buy new RAM (it just requires less than 2 million bytes)". I'm sure I have at least 4 GB of free memory so how could it be?

**Comment by azuwis** [comment]
4 GB free memory should be fine.

**Comment by azuwis** [comment]
4 GB memory should be fine. Are you using cuda or cpu for inference? Try close all other apps before running `PianoTrans.exe`, or reboot the computer, or try it on another computer.

Please give a screenshot or paste all the output here, and provide more information about your hardware and software, like:

- OS version
- CPU
- Memory
- GPU
- Audio length

**Comment by Malanced** [comment]
> 4 GB memory should be fine. Are you using cuda or cpu for inference? Try close all other apps before running `PianoTrans.exe`, or reboot the computer, or try it on another computer.
> 
> Please give a screenshot or paste all the output here, and provide more information about your hardware and software, like:
> 
> * OS version
> * CPU
> * Memory
> * GPU
> * Audio length

It fixed! many thanks~
I think it's about the virtual memory of the system disk.
