### ISSUE TITLE
Install code error?

### ISSUE THREAD

**Issue by Vaida12345** [azuwis/pianotrans#10]
Hi, I'm using a Mac with M chip, during installation, it said
<img width="743" alt="Screen Shot 2022-03-14 at 1 08 56 AM" src="https://user-images.githubusercontent.com/91354917/158070900-a3bd4466-2716-4e69-8b4d-a325f43a0b58.png">
I'm new to nix, but I managed to fix it by replacing ffmpeg with (pkgs.python3.withPackages(ps: [ ps.ffmpeg])).

**Comment by azuwis** [comment]
Fix by https://github.com/azuwis/pianotrans/commit/c97743e8cd0c812a8b11821e36c1ab9449fc46bd, thanks for the report.
