### ISSUE TITLE
not using GPU with M1-chip

### ISSUE THREAD

**Issue by Vaida12345** [azuwis/pianotrans#11]
Hi
I'm using a MacBook Pro with M1Max, but the program uses only cpu to translate. Although the speed is satisfying, and it uses only <2 cores, I wonder how I can make use of GPU.
<img width="1254" alt="Screen Shot 2022-03-14 at 1 10 37 AM" src="https://user-images.githubusercontent.com/91354917/158071040-66d5e501-128f-4e93-97af-9e3cfd532432.png">

**Comment by azuwis** [comment]
Pytorch, the machine learning framework used by piano-transcription-inference and pianotrans, does not support M1 GPU yet, see https://github.com/pytorch/pytorch/issues/47702

**Comment by Vaida12345** [comment]
> Pytorch, the machine learning framework used by piano-transcription-inference and pianotrans, does not support M1 GPU yet, see [pytorch/pytorch#47702](https://github.com/pytorch/pytorch/issues/47702)

Thanks!
