### ISSUE TITLE
I want to reduce note length

### ISSUE THREAD

**Issue by AIGLE25** [azuwis/pianotrans#13]
Hello , anyone know how to reduce note length when the sustain pedal is activated ?
![image](https://user-images.githubusercontent.com/68445450/177823778-b187d630-edf8-4cf4-aefd-a0ac3f40c6c0.png)

**Comment by greg88rx** [comment]
I agree shortening the note length (especially before the same note is stuck again) would be an improvement when playing back on a physical piano.  I've been using Logic Pro MIDI Transform tool to reduce note durations.

**Comment by azuwis** [comment]
Closing, see FAQ https://github.com/azuwis/pianotrans#faq
