### ISSUE TITLE
Double Notes

### ISSUE THREAD

**Issue by Zombieee102** [azuwis/pianotrans#14]
Hi so whenever I use this program to transcribe something as of recently it has double notes on everything being played and I have not had this problem till very recently and I've transcribed a decent amount of things using this program

**Comment by azuwis** [comment]
There are not updates recently, v1.0 was released at Feb 22.

Can you try different version, maybe try the same version on another computer?

Try transcribe an already transcribed audio, and see if the midi files are different (save a copy of the old midi file first).

I guess an odd change on your OS causes this problem.
