### ISSUE TITLE
Short Notes (Double Notes)

### ISSUE THREAD

**Issue by RemyThePianist** [azuwis/pianotrans#15]
With Old piano videos, piano videos with reverb, and pianos with weird tuning; mistake notes will appear. Or repeat the same note. 

Can you add a feature will optionally get rid of VERY VERY short notes. Aka Notes with a duration of under 1-13. 

![Duration](https://user-images.githubusercontent.com/112371170/187129555-76d0c0ca-bc0a-41e5-be67-dc5f8c84e1e3.PNG)

**Comment by azuwis** [comment]
This project is about packaging for https://github.com/bytedance/piano_transcription, as long as it gives you MIDI files, all other issues are out of scope of this project.

Feature requests should be reported to the upstream project here https://github.com/bytedance/piano_transcription/issues

I think you can filter short midi notes with other midi editing tools, e.g. Reaper Filter Events.
