### ISSUE TITLE
please build mac version

### ISSUE THREAD

**Issue by zonbar** [azuwis/pianotrans#16]
please build mac version

**Comment by azuwis** [comment]
macOS version is available using nix https://github.com/azuwis/pianotrans#how-to-use-on-linuxmacos-using-nix

If you prefer all-in-one version, you can try https://github.com/Vaida12345/PianoTranscription

**Comment by zonbar** [comment]
ok got it，i like all-in-one version,thanks

**Comment by zonbar** [comment]
OMG，it can't work on catalina,it must over 12.0

**Comment by greg88rx** [comment]
> 

I love that there is a stand alone macOS version since I had plenty of troubles with getting it to work with Nix, and it would be great if the standalone version was compatible with Big Sur or earlier flavors of the OS.
