### ISSUE TITLE
Not able to run

### ISSUE THREAD

**Issue by lo134** [azuwis/pianotrans#3]
Thank you so much for developing this all in one package. I have attempted to use this package in three different computer setups and it only worked on one (my slowest setup, using CPU). On the other two setups, when I ran pianotrans.exe, the command prompt screen flashed less than 1 second and disappeared, and nothing happened after. I am unable to select the files for conversions...etc.

Setup information (on the systems that did not work):
Windows 10
Both are laptop computers, Intel i7 Quad core processors (3rd generation on one and 4th generation on the other).
8gb of ram in one system and 16 gb of ram in the other system.
Nvidia graphics

Any ideas / guidance on getting it working on these setups will be greatly appreciated!

**Comment by azuwis** [comment]
Please run the exe in Powershell and paste the output here:

1. Right click Windows icon at bottom-left corner
2. Click `Windows Powershell`
3. Drag `PianoTrans.exe` to `Windows Powershell` window, and press `Enter`

**Comment by lo134** [comment]
Thank you for your help.

This is the output:
Traceback (most recent call last):
  File "PianoTrans.py", line 7, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "torch\__init__.py", line 81, in <module>
ImportError: DLL load failed: The operating system cannot run %1.
[8328] Failed to execute script PianoTrans

**Comment by azuwis** [comment]
Similar to https://github.com/pytorch/pytorch/issues/31324

May be caused by incompatible DLL, or maybe missing DLL.

Have you installed Microsoft Visual C++ Redistributable?

**Comment by lo134** [comment]
Yes I have installed Microsoft Visual C++ Redistributable, as the instructions stated. Not sure why in my other machine it ran without problems. They were all setup following the same process.
Do I need an existing installation of python and pytorch in the machine for the windows package gui to run properly? The machine that worked had an existing installation. In the other two machines there is no python and pytorch installed.
Thank you for your help.

    On Tuesday, May 18, 2021, 11:23:56 a.m. EDT, Zhong Jianxin ***@***.***> wrote:  
 
 


Similar to pytorch/pytorch#31324

May be caused by incompatible DLL, or maybe missing DLL.

Have you installed Microsoft Visual C++ Redistributable?

**Comment by lo134** [comment]
The issue is resolved by renaming "libiomp5md.dll" in C:\Windows\System32\libiomp5md.dll to "libiomp5md.dll.bak". This is done according to pytorch discussion thread. So far it is working well. Will continue to monitor if it give rise to other problems though.

Thank you so much for your help!

**Comment by azuwis** [comment]
I don't have `C:\Windows\System32\libiomp5md.dll` in my Windows 10 machine.

Pytorch distribute the same DLL in `torch\lib\libiomp5md.dll`, but it seems `C:\Windows\System32\libiomp5md.dll` somehow get higher priority, and cause problem.
