### ISSUE TITLE
I may find the problem.

### ISSUE THREAD

**Issue by KEARUM** [azuwis/pianotrans#5]
It works well on my friend's computer, but not mine. Its computer GPU is RTX2060 and mine is RTX3070TI, so I think the CUDA that comes with your software needs to be updated.

**Comment by KEARUM** [comment]
And the wheel version is too low too.
It can't work on a computer with RTX30 series.

**Comment by azuwis** [comment]
Please try v0.2

**Comment by azuwis** [comment]
Another user report v0.2 works for RTX 3070 Ti.
I'll close this issue, feel free to reopen if it does not work for you.
