### ISSUE TITLE
It seems it doesn't work on RTX 3000 series.

### ISSUE THREAD

**Issue by AkraidXD** [azuwis/pianotrans#6]
I tried to transcribe some audios and it gets stuck on "Using cuda for inference."

This started happening since I installed a RTX 3070 Ti. I upgraded from a RX 570, so it was using the CPU. I hoped it would work faster with the new GPU :(

OS version: Windows 10 Pro 64 bits.
CPU: Ryzen 5 3600.
Memory: 16 GB @ 3000MHz DDR4.
GPU: RTX 3070 Ti.
Audio length: N/A.

**Comment by azuwis** [comment]
Please try v0.2

**Comment by AkraidXD** [comment]
Thanks you very much!! Works like a charm, it's insane how fast it is now!
