### ISSUE TITLE
虽然MDI转出来非常准确，但是想要转成谱似乎还是很困难，而且速度固定都是100，请问这个速度可以修改吗？

### ISSUE THREAD

**Issue by MrVeryWhite** [azuwis/pianotrans#7]

**Comment by azuwis** [comment]
本项目只涉及给 https://github.com/qiuqiangkong/piano_transcription_inference 打 Windows 一体包，跟功能相关的 issue 请到上游项目提 https://github.com/qiuqiangkong/piano_transcription_inference/issues
