### ISSUE TITLE
Cannot download

### ISSUE THREAD

**Issue by Zombieee120** [azuwis/pianotrans#8]
Hi No matter how hard i try, it keeps telling me something about needing authorization to download, might you know why?

**Comment by azuwis** [comment]
The download link is provided by github just like other github projects, it works fine here.

**Comment by Zombieee120** [comment]
Yeah I get that but only this project on github tells me this I just don't understand why

**Comment by azuwis** [comment]
Have you tries v0.1? https://github.com/azuwis/pianotrans/releases/download/v0.1/PianoTrans-v0.1.zip

**Comment by Zombieee120** [comment]
I've tried all 3 versions all of them said need authorization

**Comment by Zombieee120** [comment]
I had hoped maybe an earlier version would download but it didn't

**Comment by azuwis** [comment]
Hmm, strange.

Can you provide a screenshot of the authorization page?

**Comment by Zombieee120** [comment]
It's not a page just says it on the download once it finishes

**Comment by Zombieee120** [comment]
Okay I guess it finally decided to work I had tried like 20 times before and I guess 21 did the trick

**Comment by azuwis** [comment]
Try to download on another browser, like Firefox and Google Chrome, and try on different computers at different places, like at home and at work.
